### ISSUE TITLE
Linking error on compile

### ISSUE THREAD

**Issue by NiclasEriksen** [alexfonseka/godot-fmod-integration#1]
When I try to build godot ([8698876](https://github.com/godotengine/godot/commit/869887641f3d31f19837a34da116039a26618cb0)) on Windows 10 x64, I get this error:

`[ 97%] Linking Static Library ==> modules\freetype\freetype_builtin.windows.tools.64.lib`
`[ 97%] Linking Program        ==> bin\godot.windows.tools.64.exe`
`LINK : fatal error LNK1181: cannot open input file 'fmod64_vc.windows.tools.64.lib'`
`scons: *** [bin\godot.windows.tools.64.exe] Error 1181`
`scons: building terminated because of errors.`

I have tried both x86 and x64, multithreaded on/off, same error. I have tried both Windows and Windows 10 UWP api files for fmod.

`>python --version`
`Python 3.7.2`

`>scons --version`
`        script: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36`
`        engine: v3.0.4.3a41ed6b288cee8d085373ad7fa02894e1903864, 2019-01-20 22:51:36`

**Comment by Valfather** [comment]
Same issue here.
Using python2.7

**Comment by Valfather** [comment]
I should say I'm using python2.7

**Comment by NiclasEriksen** [comment]
Found this while googling, https://github.com/godotengine/godot-docs/issues/2099. Looks like it might be an issue with scons.

**Comment by heraldofgargos** [comment]
This is an issue with Scons that only applies to the Visual Studio compiler. An easy but hacky workaround is to simply rename your library file from 'fmod64' to fmod64_vc.windows.tools.64.lib'
